#!/usr/bin/env bash

set -e

(
cd "$HOME"
cabal new-install cpkg --overwrite-policy=always
)

cpkg install pHash -vv
PKG_CONFIG_PATH="$(cpkg dump pkg-config pHash)" cabal new-install exe:phash --overwrite-policy=always
